project_id = "gcsnlxedyrlusleskjks"

[functions.identify-beyblade]
verify_jwt = false

[functions.search-beyblade]
verify_jwt = false

[functions.fetch-beyblade-details]
verify_jwt = false

[functions.beyblade-image]
verify_jwt = false
